version: '3.8'

services:
  postgres-db:
    image: postgres:14-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${DB_NAME:-inno-microservices-db}
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: inno-microservices-app
    depends_on:
      - postgres-db
      - redis
    ports:
      - "8080:8080"
    environment:
      - DB_NAME=${DB_NAME:-inno-microservices-db}
      - DB_USER=${DB_USER:-user}
      - DB_PASSWORD=${DB_PASSWORD:-password}

volumes:
  postgres_data:
  redis_data: